### ISSUE TITLE
Collect Recipe Data

### ISSUE THREAD

**Issue by JaySchall** [JaySchall/Search-A-Meal-Site#14]
Collect a large number of recipes to add to the database. All recipes should have a name, description, instructions, ingredients, and a URL link to an image. The document should be formatted so it is easy to grab recipes and add them to the database. There should be around 10-20 recipes, some with similar titles.

**Comment by gabgonz21** [comment]
[Recipe List.docx](https://github.com/JaySchall/Search-A-Meal-Site/files/11113831/Recipe.List.docx)
