### ISSUE TITLE
Create UI designs

### ISSUE THREAD

**Issue by JaySchall** [JaySchall/Search-A-Meal-Site#5]
Create UI design for main page, login, register, recipe, and user account page.

**Comment by JerGnome02** [comment]
[Account Page.pdf](https://github.com/JaySchall/Search-A-Meal-Site/files/10726747/Account.Page.pdf)
[Login.Register.pdf](https://github.com/JaySchall/Search-A-Meal-Site/files/10726748/Login.Register.pdf)
[Main Page.pdf](https://github.com/JaySchall/Search-A-Meal-Site/files/10726749/Main.Page.pdf)
[Recipe Page.pdf](https://github.com/JaySchall/Search-A-Meal-Site/files/10726750/Recipe.Page.pdf)
[Seach.Results.pdf](https://github.com/JaySchall/Search-A-Meal-Site/files/10726751/Seach.Results.pdf)
